import { Inter } from "next/font/google";
import "@/assets/js/resources";
import "@/assets/css/resources.css";
import "@/assets/scss/main.scss"


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="stylesheet" href="assets/css/vendor/fontawesome-pro.css"></link>
      <body  suppressHydrationWarning={true} className={inter.className}>{children}</body>
    </html>
  );
}
